In [1]:
!pip install TensorFlow

In [2]:
pip uninstall wrapt -y


Found existing installation: wrapt 1.14.1
Uninstalling wrapt-1.14.1:
  Successfully uninstalled wrapt-1.14.1
Note: you may need to restart the kernel to use updated packages.


You can safely remove it manually.


In [3]:
!pip install --force-reinstall wrapt==1.14.1


  Using cached wrapt-1.14.1-cp312-cp312-win_amd64.whl


In [4]:
!pip show tensorflow


Name: tensorflow
Version: 2.18.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: C:\Users\maluk\anaconda3\Lib\site-packages
Requires: tensorflow-intel
Required-by: deepface, retina-face, tf_keras


In [5]:
import tensorflow as tf
scaler=tf.constant(18)
print(scaler)

C:\Users\maluk\anaconda3\Lib\site-packages\h5py\__init__.py:36: UserWarning: h5py is running against HDF5 1.14.6 when it was built against 1.14.5, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "


tf.Tensor(18, shape=(), dtype=int32)


In [15]:
import tensorflow as tf
vector=tf.constant([1,2,3,4,5])
print(vector)

martix=tf.constant([[1,2],[3,4]])
print(martix)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [21]:
float_tensor=tf.constant([1.2,2.0,3.0], dtype=tf.float64)
print(float_tensor.dtype)



<dtype: 'float64'>


In [27]:
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
sum_tensor=tf.add(a,b)
print(sum_tensor)

product_tensor=tf.multiply(a,b)
print(product_tensor)

mean_tensor=tf.reduce_mean(tf.cast(a,dtype=tf.float32))
print(mean_tensor)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float32)
